# -*- coding: utf-8 -*-
"""Assignment_PH65117

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8WBo0H2mb3XWgEpHGuUEsOTtWwMsHJ_
"""

import csv, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv(
    "/content/proptech_raw_dataset.csv",
    engine="python",
    on_bad_lines="skip",
    quoting=csv.QUOTE_MINIMAL,
    encoding_errors="ignore"
)

print(df.shape)
display(df.head())
print(df.info())

display(df.describe(include=[np.number]).T)
display(df.describe(include=["object"]).T)

missing = pd.DataFrame({
    "missing": df.isna().sum(),
    "percent": df.isna().mean()*100
}).sort_values("percent", ascending=False)

display(missing)
print("Duplicate:", df.duplicated().sum())

num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in num_cols[:3]:
    plt.hist(df[col], bins=30); plt.title(col); plt.show()
    sns.boxplot(x=df[col]); plt.show()
    sns.violinplot(x=df[col]); plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy import stats

df_stage1 = df.copy()

def find_col(cols, keys):
    for k in keys:
        for c in cols:
            if k in c.lower():
                return c

price = find_col(df.columns, ["price"])
area = find_col(df.columns, ["area"])
rooms = find_col(df.columns, ["room"])
desc = find_col(df.columns, ["desc","description"])

df_stage1 = df_stage1.drop_duplicates()

for col in df_stage1.select_dtypes("object"):
    df_stage1[col] = df_stage1[col].str.lower().str.strip()

df_stage1.loc[df_stage1[price]<=0, price]=np.nan
df_stage1.loc[df_stage1[area]<=0, area]=np.nan
df_stage1.loc[df_stage1[rooms]<=0, rooms]=np.nan

for col in df_stage1.select_dtypes(np.number):
    df_stage1[col]=df_stage1[col].fillna(df_stage1[col].median())

for col in df_stage1.select_dtypes("object"):
    df_stage1[col]=df_stage1[col].fillna(df_stage1[col].mode()[0])

# IQR
def cap(series):
    q1,q3=series.quantile([0.25,0.75])
    iqr=q3-q1
    return series.clip(q1-1.5*iqr, q3+1.5*iqr)

for col in df_stage1.select_dtypes(np.number):
    df_stage1[col]=cap(df_stage1[col])

# Z-score
z = np.abs(stats.zscore(df_stage1.select_dtypes(np.number)))
df_stage1 = df_stage1[(z < 3).all(axis=1)]

# text duplicate
tfidf = TfidfVectorizer(max_features=300)
X = tfidf.fit_transform(df_stage1[desc].astype(str).head(200))
sim = cosine_similarity(X)

pairs=[]
for i in range(len(sim)):
    for j in range(i+1,len(sim)):
        if sim[i,j]>0.85:
            pairs.append((i,j))

print("Duplicate text pairs:", pairs[:5])

print(df_stage1.shape)

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

df_stage1_copy = df_stage1.copy()

num_cols = df_stage1_copy.select_dtypes(np.number).columns
scaler = MinMaxScaler()
df_stage1_copy[num_cols]=scaler.fit_transform(df_stage1_copy[num_cols])

cat_cols = df_stage1_copy.select_dtypes("object").columns
for col in cat_cols:
    if col!=desc:
        df_stage1_copy[col]=LabelEncoder().fit_transform(df_stage1_copy[col])

tfidf = TfidfVectorizer(max_features=200)
tfidf_matrix = tfidf.fit_transform(df_stage1_copy[desc].astype(str))

print(tfidf_matrix.shape)

import zipfile
import numpy as np
import pandas as pd
from PIL import Image

def find_col(cols, keys):
    for k in keys:
        for c in cols:
            if k in c.lower():
                return c
    return None

if "df_stage1" in globals():
    df_stage2 = df_stage1.copy()
else:
    df_stage2 = df.copy()

price = find_col(df_stage2.columns, ["price"])
area = find_col(df_stage2.columns, ["area"])
rooms = find_col(df_stage2.columns, ["room"])
desc = find_col(df_stage2.columns, ["desc", "description"])
date_col = find_col(df_stage2.columns, ["date"])
img_col = find_col(df_stage2.columns, ["image"])

if date_col is not None:
    df_stage2[date_col] = pd.to_datetime(df_stage2[date_col], errors="coerce")
    df_stage2["month"] = df_stage2[date_col].dt.month
    df_stage2["quarter"] = df_stage2[date_col].dt.quarter
    df_stage2["dayofweek"] = df_stage2[date_col].dt.dayofweek

if desc is not None:
    df_stage2["word_count"] = df_stage2[desc].astype(str).apply(lambda x: len(x.split()))
    df_stage2["luxury"] = df_stage2[desc].astype(str).str.contains("luxury", case=False, na=False).astype(int)
    df_stage2["cozy"] = df_stage2[desc].astype(str).str.contains("cozy", case=False, na=False).astype(int)

ZIP = "/content/images.zip"

def img_feat(name):
    try:
        with zipfile.ZipFile(ZIP) as z:
            candidates = [str(name), f"images/{name}"]
            target = None
            for c in candidates:
                if c in z.namelist():
                    target = c
                    break
            if target is None:
                return np.nan

            with z.open(target) as f:
                img = Image.open(f).convert("RGB").resize((32, 32))
                arr = np.array(img)
                return arr.mean()
    except:
        return np.nan

if img_col is not None:
    df_stage2["img_mean"] = df_stage2[img_col].apply(img_feat)

if price is not None and area is not None:
    df_stage2["price_per_m2"] = df_stage2[price] / df_stage2[area]

if price is not None:
    df_stage2["log_price"] = np.log1p(df_stage2[price])

if area is not None and rooms is not None:
    df_stage2["interaction_area_room"] = df_stage2[area] * df_stage2[rooms]

print(df_stage2.shape)
display(df_stage2.head())

!pip -q install xgboost

import math
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

# =========================
# DÙNG DATA NHỎ HƠN ĐỂ TRAIN
# =========================
df_model = df_stage2.copy()

# Lấy mẫu 100000 dòng cho Colab chạy nhanh hơn
if len(df_model) > 100000:
    df_model = df_model.sample(100000, random_state=42)

# Bỏ cột img_mean nếu toàn missing
if "img_mean" in df_model.columns:
    if df_model["img_mean"].isna().all():
        df_model = df_model.drop(columns=["img_mean"])

# Xác định cột target
price_col = None
for c in df_model.columns:
    if "price" in c.lower():
        price_col = c
        break

# Xác định cột text
desc_col = None
for c in df_model.columns:
    if "desc" in c.lower() or "description" in c.lower():
        desc_col = c
        break

X = df_model.drop(columns=[price_col], errors="ignore")
y = df_model[price_col]

num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(include=["object"]).columns.tolist()

if desc_col in cat_cols:
    cat_cols.remove(desc_col)

num_transform = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_transform = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

transformers = [
    ("num", num_transform, num_cols),
    ("cat", cat_transform, cat_cols)
]

pre = ColumnTransformer(transformers)

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.3, random_state=42)

models = {
    "LR": LinearRegression(),
    "RF": RandomForestRegressor(n_estimators=30, max_depth=10, random_state=42, n_jobs=-1),
    "GB": GradientBoostingRegressor(n_estimators=50, random_state=42),
    "XGB": XGBRegressor(
        n_estimators=50,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )
}

results = []

for name, m in models.items():
    pipe = Pipeline([
        ("pre", pre),
        ("m", m)
    ])

    pipe.fit(Xtr, ytr)
    pred = pipe.predict(Xte)

    rmse = math.sqrt(mean_squared_error(yte, pred))
    mae = mean_absolute_error(yte, pred)
    r2 = r2_score(yte, pred)

    results.append([name, rmse, mae, r2])

results_df = pd.DataFrame(results, columns=["Model", "RMSE", "MAE", "R2"]).sort_values("RMSE")
display(results_df)

import seaborn as sns

# KPI
print(df_stage2.groupby(find_col(df_stage2.columns,["district"]))[price].mean().head())

# top 5%
top=df_stage2[df_stage2[price]>df_stage2[price].quantile(0.95)]
display(top.head())

# plot
sns.histplot(df_stage2[price]); plt.show()
sns.histplot(np.log1p(df_stage2[price])); plt.show()

import math
import numpy as np
import pandas as pd

from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

df_final = df_stage2.copy()

price_col = None
for c in df_final.columns:
    if "price" in c.lower():
        price_col = c
        break

area_col = None
room_col = None
for c in df_final.columns:
    if "area" in c.lower():
        area_col = c
    if "room" in c.lower():
        room_col = c

for col in df_final.columns:
    if pd.api.types.is_datetime64_any_dtype(df_final[col]):
        df_final[col] = df_final[col].astype("int64") // 10**9

num_cols = df_final.select_dtypes(include=[np.number]).columns.tolist()

if price_col in num_cols:
    transform_cols = [c for c in num_cols if c != price_col]
else:
    transform_cols = num_cols.copy()

df_final[transform_cols] = df_final[transform_cols].replace([np.inf, -np.inf], np.nan)

for col in transform_cols:
    df_final[col] = df_final[col].fillna(df_final[col].median())

valid_transform_cols = [c for c in transform_cols if df_final[c].nunique() > 1]

if len(valid_transform_cols) > 0:
    pt = PowerTransformer(method="yeo-johnson", standardize=True)
    df_final[valid_transform_cols] = pt.fit_transform(df_final[valid_transform_cols])

if area_col is not None and room_col is not None:
    df_final["interaction"] = df_final[area_col] * df_final[room_col]

if len(df_final) > 30000:
    df_final = df_final.sample(30000, random_state=42)

X_num = df_final.select_dtypes(include=[np.number]).drop(columns=[price_col], errors="ignore")
y = df_final[price_col]

Xtr1, Xte1, ytr1, yte1 = train_test_split(X_num, y, test_size=0.3, random_state=42)

m1 = RandomForestRegressor(n_estimators=30, max_depth=10, random_state=42, n_jobs=-1)
m1.fit(Xtr1, ytr1)
pred1 = m1.predict(Xte1)

rmse_num = math.sqrt(mean_squared_error(yte1, pred1))

X_full = df_final.drop(columns=[price_col], errors="ignore").copy()

for col in X_full.columns:
    if pd.api.types.is_datetime64_any_dtype(X_full[col]):
        X_full[col] = X_full[col].astype("int64") // 10**9

X_full = pd.get_dummies(X_full, drop_first=True)
X_full = X_full.replace([np.inf, -np.inf], np.nan)
X_full = X_full.fillna(X_full.median(numeric_only=True))
X_full = X_full.fillna(0)

Xtr2, Xte2, ytr2, yte2 = train_test_split(X_full, y, test_size=0.3, random_state=42)

m2 = RandomForestRegressor(n_estimators=30, max_depth=10, random_state=42, n_jobs=-1)
m2.fit(Xtr2, ytr2)
pred2 = m2.predict(Xte2)

rmse_full = math.sqrt(mean_squared_error(yte2, pred2))

print("Numerical only RMSE:", rmse_num)
print("Full feature RMSE:", rmse_full)
display(df_final.head())