# -*- coding: utf-8 -*-
"""Lab2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfBxsnUYfhKg65V9yXYesppw89YiK5jg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import zscore

housing = pd.read_csv("/ITA105_Lab_2_Housing.csv")
iot = pd.read_csv("/ITA105_Lab_2_Iot.csv")
ecom = pd.read_csv("/ITA105_Lab_2_Ecommerce.csv")

print(housing.shape)
print(housing.describe())

# Boxplot
housing.boxplot()
plt.show()

# Z-score tìm outlier
z = zscore(housing.select_dtypes(include=np.number))
print("Outlier:", (abs(z)>3).sum())

iot["timestamp"] = pd.to_datetime(iot["timestamp"])
iot = iot.set_index("timestamp")

# Vẽ nhiệt độ
iot["temperature"].plot()
plt.show()

# Rolling phát hiện outlier
mean = iot["temperature"].rolling(10).mean()
std = iot["temperature"].rolling(10).std()

outlier = (iot["temperature"] > mean+3*std) | (iot["temperature"] < mean-3*std)
print("Outlier:", outlier.sum())

# Xử lý
iot["temperature"] = iot["temperature"].interpolate()

print(ecom.describe())

# Boxplot
ecom.boxplot()
plt.show()

# Xử lý dữ liệu lỗi
ecom = ecom[ecom["price"] > 0]
ecom = ecom[ecom["quantity"] >= 0]
ecom = ecom[(ecom["rating"] >= 0) & (ecom["rating"] <= 5)]

# Z-score
z = zscore(ecom[["price","quantity","rating"]])
print("Outlier:", (abs(z)>3).sum())

cols = housing.select_dtypes(include=np.number).columns

z1 = zscore(housing[cols[0]])
z2 = zscore(housing[cols[1]])

multi = (abs(z1) > 3) & (abs(z2) > 3)

print("Multi outlier:", multi.sum())

plt.scatter(housing[cols[0]], housing[cols[1]], c=multi)
plt.show()