# -*- coding: utf-8 -*-
"""Lab3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjdIz65_-QLxB_nfjXA-ZLbT-TRBEJSR
"""

# Bài 1:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler

sports = pd.read_csv("/content/ITA105_Lab_3_Sports.csv")
health = pd.read_csv("/content/ITA105_Lab_3_Health (1).csv")
finance = pd.read_csv("/content/ITA105_Lab_3_Finance.csv")
gaming = pd.read_csv("/content/ITA105_Lab_3_Gaming.csv")

print(sports.head())
print(sports.isnull().sum())
print(sports.describe())

sports.hist(figsize=(10,6))
plt.tight_layout()
plt.show()

sports.plot(kind="box", subplots=True, layout=(2,3), figsize=(10,6))
plt.tight_layout()
plt.show()

minmax = MinMaxScaler()
sports_minmax = pd.DataFrame(minmax.fit_transform(sports), columns=sports.columns)

zscore = StandardScaler()
sports_zscore = pd.DataFrame(zscore.fit_transform(sports), columns=sports.columns)

print(sports_minmax.head())
print(sports_zscore.head())

for col in sports.columns:
    plt.figure(figsize=(8,3))
    plt.hist(sports[col], alpha=0.5, label="Gốc")
    plt.hist(sports_minmax[col], alpha=0.5, label="MinMax")
    plt.hist(sports_zscore[col], alpha=0.5, label="ZScore")
    plt.title(col)
    plt.legend()
    plt.show()

# Bài 2:
print(health.head())
print(health.isnull().sum())
print(health.describe())

health.hist(figsize=(10,6))
plt.tight_layout()
plt.show()

health.plot(kind="box", subplots=True, layout=(2,2), figsize=(10,6))
plt.tight_layout()
plt.show()

# tìm ngoại lệ đơn giản bằng boxplot hoặc mô tả
# chuẩn hóa
minmax = MinMaxScaler()
health_minmax = pd.DataFrame(minmax.fit_transform(health), columns=health.columns)

zscore = StandardScaler()
health_zscore = pd.DataFrame(zscore.fit_transform(health), columns=health.columns)

for col in health.columns:
    plt.figure(figsize=(8,3))
    plt.hist(health[col], alpha=0.5, label="Gốc")
    plt.hist(health_minmax[col], alpha=0.5, label="MinMax")
    plt.hist(health_zscore[col], alpha=0.5, label="ZScore")
    plt.title(col)
    plt.legend()
    plt.show()

# Bài 3:
print(finance.head())
print(finance.isnull().sum())
print(finance.describe())

finance.plot(kind="box", subplots=True, layout=(2,2), figsize=(10,6))
plt.tight_layout()
plt.show()

minmax = MinMaxScaler()
finance_minmax = pd.DataFrame(minmax.fit_transform(finance), columns=finance.columns)

zscore = StandardScaler()
finance_zscore = pd.DataFrame(zscore.fit_transform(finance), columns=finance.columns)

# scatter trước chuẩn hóa
plt.figure(figsize=(5,4))
plt.scatter(finance["doanh_thu_musd"], finance["loi_nhuan_musd"])
plt.xlabel("doanh_thu_musd")
plt.ylabel("loi_nhuan_musd")
plt.title("Trước chuẩn hóa")
plt.show()

# scatter sau Min-Max
plt.figure(figsize=(5,4))
plt.scatter(finance_minmax["doanh_thu_musd"], finance_minmax["loi_nhuan_musd"])
plt.xlabel("doanh_thu_musd")
plt.ylabel("loi_nhuan_musd")
plt.title("Sau Min-Max")
plt.show()

# scatter sau Z-Score
plt.figure(figsize=(5,4))
plt.scatter(finance_zscore["doanh_thu_musd"], finance_zscore["loi_nhuan_musd"])
plt.xlabel("doanh_thu_musd")
plt.ylabel("loi_nhuan_musd")
plt.title("Sau Z-Score")
plt.show()

# Bài 4:
print(gaming.head())
print(gaming.isnull().sum())
print(gaming.describe())

gaming.hist(figsize=(10,6))
plt.tight_layout()
plt.show()

gaming.plot(kind="box", subplots=True, layout=(2,2), figsize=(10,6))
plt.tight_layout()
plt.show()

minmax = MinMaxScaler()
gaming_minmax = pd.DataFrame(minmax.fit_transform(gaming), columns=gaming.columns)

zscore = StandardScaler()
gaming_zscore = pd.DataFrame(zscore.fit_transform(gaming), columns=gaming.columns)

for col in gaming.columns:
    plt.figure(figsize=(8,3))
    plt.hist(gaming[col], alpha=0.5, label="Gốc")
    plt.hist(gaming_minmax[col], alpha=0.5, label="MinMax")
    plt.hist(gaming_zscore[col], alpha=0.5, label="ZScore")
    plt.title(col)
    plt.legend()
    plt.show()