# -*- coding: utf-8 -*-
"""Lab4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nsa_qyO0PY_jt28vhs5ooHv8hwUUjSD4
"""

!pip install gensim

import pandas as pd
import re
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec

hotel = pd.read_csv("/content/ITA105_Lab_4_Hotel_reviews.csv")
match = pd.read_csv("/content/ITA105_Lab_4_Match_comments.csv")
player = pd.read_csv("/content/ITA105_Lab_4_Player_feedback.csv")
album = pd.read_csv("/content/ITA105_Lab_4_Album_reviews.csv")

stop_words = {
    "và","là","có","nhưng","rất","khá","được","thì","ở","của","cho","với",
    "này","kia","đó","một","những","các","đã","hay","khi","vẫn","hơi"
}

def clean_text(text):
    text = str(text).lower()

    text = text.replace("sạch sẽ", "sạch_sẽ")
    text = text.replace("xuất sắc", "xuất_sắc")
    text = text.replace("sáng tạo", "sáng_tạo")

    text = re.sub(r"[^\w\s]", "", text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return words

# Bài 1:

print(hotel.isnull().sum())

le = LabelEncoder()
hotel["hotel_name_encoded"] = le.fit_transform(hotel["hotel_name"])
hotel["customer_type_encoded"] = le.fit_transform(hotel["customer_type"])

hotel["clean"] = hotel["review_text"].apply(clean_text)

tfidf = TfidfVectorizer()
hotel_tfidf = tfidf.fit_transform(hotel["review_text"].astype(str))
print("TF-IDF shape:", hotel_tfidf.shape)

hotel_w2v = Word2Vec(sentences=hotel["clean"], vector_size=50, window=3, min_count=1)

print("5 tu gan nghia voi sach_se:")
print(hotel_w2v.wv.most_similar("sạch_sẽ", topn=5))

# Bài 2:

le = LabelEncoder()
match["team_encoded"] = le.fit_transform(match["team"])
match["author_encoded"] = le.fit_transform(match["author"])

match["clean"] = match["comment_text"].apply(clean_text)

tfidf = TfidfVectorizer()
match_tfidf = tfidf.fit_transform(match["comment_text"].astype(str))
print("TF-IDF shape:", match_tfidf.shape)

match_w2v = Word2Vec(sentences=match["clean"], vector_size=50, window=3, min_count=1)

print("5 tu gan nghia voi xuat_sac:")
print(match_w2v.wv.most_similar("xuất_sắc", topn=5))

# Bài 3: PLAYER

le = LabelEncoder()
player["player_type_encoded"] = le.fit_transform(player["player_type"])
player["device_encoded"] = le.fit_transform(player["device"])

player["clean"] = player["feedback_text"].apply(clean_text)

tfidf = TfidfVectorizer()
player_tfidf = tfidf.fit_transform(player["feedback_text"].astype(str))
print("TF-IDF shape:", player_tfidf.shape)

player_w2v = Word2Vec(sentences=player["clean"], vector_size=50, window=3, min_count=1)

print("5 tu gan nghia voi dep:")
print(player_w2v.wv.most_similar("đẹp", topn=5))

# Bài 4: Album

le = LabelEncoder()
album["genre_encoded"] = le.fit_transform(album["genre"])
album["platform_encoded"] = le.fit_transform(album["platform"])

album["clean"] = album["review_text"].apply(clean_text)

tfidf = TfidfVectorizer()
album_tfidf = tfidf.fit_transform(album["review_text"].astype(str))
print("TF-IDF shape:", album_tfidf.shape)

album_w2v = Word2Vec(sentences=album["clean"], vector_size=50, window=3, min_count=1)

print("5 tu gan nghia voi sang_tao:")
print(album_w2v.wv.most_similar("sáng_tạo", topn=5))