# -*- coding: utf-8 -*-
"""Lab5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K66UVsojTC50-hFSO4IY9C42xoWr4tgy
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose

supermarket = pd.read_csv("/content/ITA105_Lab_5_Supermarket.csv")
web = pd.read_csv("/content/ITA105_Lab_5_Web_traffic.csv")
stock = pd.read_csv("/content/ITA105_Lab_5_Stock.csv")
production = pd.read_csv("/content/ITA105_Lab_5_Production.csv")

print("BAI 1 - SUPERMARKET")

supermarket["date"] = pd.to_datetime(supermarket["date"])
supermarket = supermarket.set_index("date")

print(supermarket.isnull().sum())

supermarket["revenue"] = supermarket["revenue"].interpolate()

supermarket["year"] = supermarket.index.year
supermarket["month"] = supermarket.index.month
supermarket["quarter"] = supermarket.index.quarter
supermarket["day_of_week"] = supermarket.index.dayofweek
supermarket["is_weekend"] = supermarket.index.dayofweek >= 5

print(supermarket.head())

monthly_revenue = supermarket["revenue"].resample("M").sum()
weekly_revenue = supermarket["revenue"].resample("W").sum()

plt.figure(figsize=(10,4))
monthly_revenue.plot()
plt.title("Tong doanh thu theo thang")
plt.show()

plt.figure(figsize=(10,4))
weekly_revenue.plot()
plt.title("Tong doanh thu theo tuan")
plt.show()

supermarket["rolling_30"] = supermarket["revenue"].rolling(30).mean()

plt.figure(figsize=(10,4))
plt.plot(supermarket.index, supermarket["revenue"], label="Revenue")
plt.plot(supermarket.index, supermarket["rolling_30"], label="Rolling 30", color="red")
plt.legend()
plt.title("Trend doanh thu")
plt.show()

season_month = supermarket.groupby("month")["revenue"].mean()
print(season_month)

season_month.plot(kind="bar", figsize=(8,4), title="Seasonality theo thang")
plt.show()

print("BAI 2 - WEB TRAFFIC")

web["datetime"] = pd.to_datetime(web["datetime"])
web = web.set_index("datetime")

web = web.asfreq("H")

print(web.isnull().sum())

web["visits"] = web["visits"].interpolate()

web["hour"] = web.index.hour
web["day_of_week"] = web.index.dayofweek

print(web.head())

plt.figure(figsize=(10,4))
web["visits"].plot()
plt.title("Luu luong website")
plt.show()

hourly_avg = web.groupby("hour")["visits"].mean()
print(hourly_avg)

hourly_avg.plot(kind="bar", figsize=(8,4), title="Luu luong trung binh theo gio")
plt.show()

weekly_avg = web.groupby("day_of_week")["visits"].mean()
print(weekly_avg)

weekly_avg.plot(kind="bar", figsize=(8,4), title="Luu luong trung binh theo ngay trong tuan")
plt.show()

print("BAI 3 - STOCK")

stock["date"] = pd.to_datetime(stock["date"])
stock = stock.set_index("date")

stock = stock.asfreq("D")

print(stock.isnull().sum())

stock["close_price"] = stock["close_price"].ffill()

print(stock.head())

plt.figure(figsize=(10,4))
stock["close_price"].plot()
plt.title("Gia dong cua")
plt.show()

stock["rolling_7"] = stock["close_price"].rolling(7).mean()
stock["rolling_30"] = stock["close_price"].rolling(30).mean()

plt.figure(figsize=(10,4))
plt.plot(stock.index, stock["close_price"], label="Close price")
plt.plot(stock.index, stock["rolling_7"], label="Rolling 7")
plt.plot(stock.index, stock["rolling_30"], label="Rolling 30")
plt.legend()
plt.title("Trend gia co phieu")
plt.show()

stock["month"] = stock.index.month
monthly_pattern = stock.groupby("month")["close_price"].mean()

print(monthly_pattern)

monthly_pattern.plot(kind="bar", figsize=(8,4), title="Pattern lap lai theo thang")
plt.show()

print("BAI 4 - PRODUCTION")

production["week_start"] = pd.to_datetime(production["week_start"])
production = production.set_index("week_start")

print(production.isnull().sum())

production["production"] = production["production"].interpolate()

production["week"] = production.index.isocalendar().week
production["quarter"] = production.index.quarter
production["year"] = production.index.year

print(production.head())

production["rolling_4"] = production["production"].rolling(4).mean()

plt.figure(figsize=(10,4))
plt.plot(production.index, production["production"], label="Production")
plt.plot(production.index, production["rolling_4"], label="Rolling 4", color="red")
plt.legend()
plt.title("Trend san xuat cong nghiep")
plt.show()

quarter_avg = production.groupby("quarter")["production"].mean()
print(quarter_avg)

quarter_avg.plot(kind="bar", figsize=(8,4), title="Seasonality theo quy")
plt.show()

result = seasonal_decompose(production["production"], model="additive", period=13)
result.plot()
plt.show()