# -*- coding: utf-8 -*-
"""Lab6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zN1QDSbyKfPOMZPr63l8GsGzv8SmFYWK
"""

import os
import random
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageEnhance, ImageOps

IMG_SIZE = (224, 224)

def load_images(folder):
    imgs = []
    for file in os.listdir(folder):
        if file.endswith((".jpg",".png",".jpeg")):
            path = os.path.join(folder, file)
            img = Image.open(path).convert("RGB")
            imgs.append(img)
    return imgs

def resize(img):
    return img.resize(IMG_SIZE)

def normalize(img):
    return np.array(img)/255.0

def show(imgs, title=""):
    plt.figure(figsize=(10,4))
    for i,img in enumerate(imgs):
        plt.subplot(1,len(imgs),i+1)
        if isinstance(img,np.ndarray):
            plt.imshow(img, cmap='gray')
        else:
            plt.imshow(img)
        plt.axis("off")
    plt.suptitle(title)
    plt.show()

from PIL import Image, ImageEnhance, ImageOps
import numpy as np
import matplotlib.pyplot as plt
import random

path = "/content/z7725970905909_0da64fae1c1cf3f98b83bcc59803040f.jpg"

img = Image.open(path).convert("RGB")

# resize
img = img.resize((224,224))

# flip
if random.random()>0.5:
    img = ImageOps.mirror(img)

# rotate
img = img.rotate(random.randint(-15,15))

# brightness
enhancer = ImageEnhance.Brightness(img)
img = enhancer.enhance(random.uniform(0.8,1.2))

# grayscale
img = ImageOps.grayscale(img)

# normalize
img_norm = np.array(img)/255.0

# show
plt.imshow(img, cmap='gray')
plt.axis("off")
plt.show()

from PIL import Image, ImageEnhance
import numpy as np
import matplotlib.pyplot as plt
import random

path = "/content/z7725970840189_818347ab17741f5ec3311ad9e49e1411.jpg"

def add_gaussian_noise(img):
    arr = np.array(img).astype(np.float32)
    noise = np.random.normal(0, 15, arr.shape)
    arr = arr + noise
    arr = np.clip(arr, 0, 255).astype(np.uint8)
    return Image.fromarray(arr)

img = Image.open(path).convert("RGB")
img = img.resize((224, 224))

img = add_gaussian_noise(img)

enhancer = ImageEnhance.Brightness(img)
img = enhancer.enhance(random.uniform(0.85, 1.15))

img = img.rotate(random.randint(-10, 10))

img_norm = np.array(img) / 255.0

plt.imshow(img)
plt.axis("off")
plt.show()

print(img_norm.shape)
print(img_norm.min(), img_norm.max())

from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt
import random

# đường dẫn đúng tới 1 file ảnh
path = "/content/z7725970862561_4ed3cf82e1a71a17790ea76e4b35804b.jpg"

# đọc ảnh
img = Image.open(path).convert("RGB")
img = img.resize((224, 224))

# hàm crop ngẫu nhiên
def random_crop(img):
    w, h = img.size
    new_w = int(w * 0.8)
    new_h = int(h * 0.8)
    left = random.randint(0, w - new_w)
    top = random.randint(0, h - new_h)
    right = left + new_w
    bottom = top + new_h
    return img.crop((left, top, right, bottom)).resize((224, 224))

# hàm zoom
def zoom_image(img):
    w, h = img.size
    scale = random.uniform(1.0, 1.2)
    new_w = int(w * scale)
    new_h = int(h * scale)

    zoomed = img.resize((new_w, new_h))

    left = (new_w - 224) // 2
    top = (new_h - 224) // 2
    right = left + 224
    bottom = top + 224

    return zoomed.crop((left, top, right, bottom))

aug_imgs = []
norm_imgs = []

for i in range(9):
    temp = img.copy()

    # flip
    if random.random() > 0.5:
        temp = ImageOps.mirror(temp)

    # random crop
    temp = random_crop(temp)

    # zoom
    temp = zoom_image(temp)

    # rotation
    temp = temp.rotate(random.randint(-15, 15))

    aug_imgs.append(temp)
    norm_imgs.append(np.array(temp) / 255.0)

# hiển thị grid 3x3
plt.figure(figsize=(8, 8))
for i in range(9):
    plt.subplot(3, 3, i + 1)
    plt.imshow(aug_imgs[i])
    plt.axis("off")
plt.suptitle("Bài 3 - Grid 3x3 ảnh augmentation")
plt.show()

print("Kích thước ảnh đầu tiên:", norm_imgs[0].shape)
print("Min pixel:", norm_imgs[0].min())
print("Max pixel:", norm_imgs[0].max())

from PIL import Image, ImageEnhance, ImageOps
import numpy as np
import matplotlib.pyplot as plt
import random

path = "/content/z7725970862556_0d9b414a34e0b914c542c555557dbcab.jpg"

img = Image.open(path).convert("RGB")

img = img.resize((224, 224))

aug_imgs = []
norm_imgs = []

for i in range(3):
    temp = img.copy()

    temp = temp.rotate(random.randint(-15, 15))

    if random.random() > 0.5:
        temp = ImageOps.mirror(temp)

    enhancer = ImageEnhance.Brightness(temp)
    temp = enhancer.enhance(random.uniform(0.8, 1.2))

    temp = ImageOps.grayscale(temp)

    aug_imgs.append(temp)
    norm_imgs.append(np.array(temp) / 255.0)

plt.figure(figsize=(4, 4))
plt.imshow(img)
plt.axis("off")
plt.title("Ảnh gốc")
plt.show()

plt.figure(figsize=(12, 4))
for i in range(3):
    plt.subplot(1, 3, i + 1)
    plt.imshow(aug_imgs[i], cmap="gray")
    plt.axis("off")
plt.suptitle("Bài 4 - 3 ảnh augmentation")
plt.show()

print("Kích thước ảnh đầu tiên:", norm_imgs[0].shape)
print("Min pixel:", norm_imgs[0].min())
print("Max pixel:", norm_imgs[0].max())