# -*- coding: utf-8 -*-
"""Lab7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdIKEFaTCDCDNYqpdRGHKNQIypHzlzD1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import boxcox
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("/content/ITA105_Lab_7.csv")

# Bài 1:
num_cols = df.select_dtypes(include=np.number).columns

skew_table = pd.DataFrame({
    "Column": num_cols,
    "Skewness": [df[col].skew() for col in num_cols]
})

skew_table["AbsSkew"] = skew_table["Skewness"].abs()
skew_table = skew_table.sort_values("AbsSkew", ascending=False)

print(skew_table.head(10))

top3 = skew_table.head(3)["Column"].tolist()

for col in top3:
    plt.figure(figsize=(6,4))
    plt.hist(df[col], bins=30, alpha=0.7, density=True)
    df[col].plot(kind="kde")
    plt.title(col)
    plt.show()

# Bài 2:
# 2 cột dương
col1 = "LotArea"
col2 = "SalePrice"

# 1 cột có âm
col3 = "NegSkewIncome"

compare = []

for col in [col1, col2]:
    original = df[col]
    log_col = np.log(original)
    boxcox_col, lam = boxcox(original)

    pt = PowerTransformer(method="yeo-johnson")
    power_col = pt.fit_transform(df[[col]]).flatten()

    compare.append([col,
                    original.skew(),
                    pd.Series(log_col).skew(),
                    pd.Series(boxcox_col).skew(),
                    pd.Series(power_col).skew(),
                    lam])

    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    plt.hist(original, bins=30)
    plt.title("Before " + col)

    plt.subplot(1,2,2)
    plt.hist(boxcox_col, bins=30)
    plt.title("After BoxCox " + col)

    plt.show()

pt = PowerTransformer(method="yeo-johnson")
power_neg = pt.fit_transform(df[[col3]]).flatten()

compare.append([col3,
                df[col3].skew(),
                "khong dung",
                "khong dung",
                pd.Series(power_neg).skew(),
                "khong co"])

compare_table = pd.DataFrame(compare, columns=[
    "Column", "Skew_before", "Skew_log", "Skew_boxcox", "Skew_power", "Lambda"
])

print(compare_table)

# Bài 3:
data_model = df.select_dtypes(include=np.number)

X = data_model.drop("SalePrice", axis=1)
y = data_model["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_a = LinearRegression()
model_a.fit(X_train, y_train)
pred_a = model_a.predict(X_test)

rmse_a = np.sqrt(mean_squared_error(y_test, pred_a))
r2_a = r2_score(y_test, pred_a)

print("A - RMSE:", rmse_a)
print("A - R2:", r2_a)

y_train_log = np.log(y_train)

model_b = LinearRegression()
model_b.fit(X_train, y_train_log)

pred_b_log = model_b.predict(X_test)
pred_b = np.exp(pred_b_log)

rmse_b = np.sqrt(mean_squared_error(y_test, pred_b))
r2_b = r2_score(y_test, pred_b)

print("B - RMSE:", rmse_b)
print("B - R2:", r2_b)

X_train_c = X_train.copy()
X_test_c = X_test.copy()

skew_cols = X_train.columns[X_train.skew().abs() > 1]

pt = PowerTransformer(method="yeo-johnson")
X_train_c[skew_cols] = pt.fit_transform(X_train_c[skew_cols])
X_test_c[skew_cols] = pt.transform(X_test_c[skew_cols])

model_c = LinearRegression()
model_c.fit(X_train_c, y_train)
pred_c = model_c.predict(X_test_c)

rmse_c = np.sqrt(mean_squared_error(y_test, pred_c))
r2_c = r2_score(y_test, pred_c)

print("C - RMSE:", rmse_c)
print("C - R2:", r2_c)

result = pd.DataFrame({
    "Model": ["Raw", "Log Target", "Power Transform"],
    "RMSE": [rmse_a, rmse_b, rmse_c],
    "R2": [r2_a, r2_b, r2_c]
})

print(result)

# Bài 4:
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(df["LotArea"], bins=30)
plt.title("Raw LotArea")

plt.subplot(1,2,2)
plt.hist(np.log(df["LotArea"]), bins=30)
plt.title("Log LotArea")

plt.show()

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(df["SalePrice"], bins=30)
plt.title("Raw SalePrice")

plt.subplot(1,2,2)
plt.hist(np.log(df["SalePrice"]), bins=30)
plt.title("Log SalePrice")

plt.show()

df["log_price_index"] = np.log(df["SalePrice"]) / np.log(df["LotArea"])
print(df[["SalePrice", "LotArea", "log_price_index"]].head())