# -*- coding: utf-8 -*-
"""Lab8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BOWE5dSqWjcJCDdBuY_sRltgBJzOU91
"""

import numpy as np
import pandas as pd
import joblib

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PowerTransformer, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import KFold, cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/ITA105_Lab_8.csv")

target = "SalePrice"
num_cols = ["LotArea", "Rooms", "HasGarage", "NoiseFeature"]
cat_cols = ["Neighborhood", "Condition"]
text_col = "Description"
date_col = "SaleDate"

X = df.drop(columns=[target])
y = df[target]

# Bài 1:
X_demo = X.head(10)
X_demo_new = preprocessor.fit_transform(X_demo)

print("Smoke test OK")
print("Shape:", X_demo_new.shape)

num_features = num_cols
cat_features = list(preprocessor.named_transformers_["cat"]["onehot"].get_feature_names_out(cat_cols))
text_features = list(preprocessor.named_transformers_["txt"]["tfidf"].get_feature_names_out())
date_features = ["month", "quarter"]

all_features = num_features + cat_features + text_features + date_features

print("Feature names:")
print(all_features)

# Bài 2:
test1 = X.sample(10, random_state=1).copy()
test2 = X.sample(10, random_state=2).copy()
test2["LotArea"] = np.nan
test3 = X.sample(10, random_state=3).copy()
test3["Neighborhood"] = "NewPlace"
test4 = X.sample(10, random_state=4).copy()
test4["LotArea"] = "abc"
test5 = X.sample(10, random_state=5).copy()
test5["LotArea"] = test5["LotArea"] * 100

tests = {
    "full": test1,
    "missing": test2,
    "unseen": test3,
    "wrong_type": test4,
    "skewed": test5
}

preprocessor.fit(X)

for name, data in tests.items():
    try:
        out = preprocessor.transform(data)
        print(name, "OK", out.shape)
    except Exception as e:
        print(name, "ERROR:", e)

print("Nhận xét:")
print("- missing: xử lý bằng imputer")
print("- unseen category: xử lý bằng handle_unknown='ignore'")
print("- wrong type: có thể lỗi nếu cột số chứa chuỗi")
print("- output cuối là ma trận số để đưa vào model")

# Bài 3:
pipe_lr = Pipeline([
    ("prep", preprocessor),
    ("model", LinearRegression())
])

pipe_rf = Pipeline([
    ("prep", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

cv = KFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    "rmse": "neg_root_mean_squared_error",
    "mae": "neg_mean_absolute_error",
    "r2": "r2"
}

cv_lr = cross_validate(pipe_lr, X, y, cv=cv, scoring=scoring)
cv_rf = cross_validate(pipe_rf, X, y, cv=cv, scoring=scoring)

print("Linear Regression")
print("RMSE:", -cv_lr["test_rmse"].mean())
print("MAE :", -cv_lr["test_mae"].mean())
print("R2  :", cv_lr["test_r2"].mean())

print("\nRandom Forest")
print("RMSE:", -cv_rf["test_rmse"].mean())
print("MAE :", -cv_rf["test_mae"].mean())
print("R2  :", cv_rf["test_r2"].mean())

print("Nhận xét:")
print("- Pipeline giúp giảm lỗi xử lý thủ công")
print("- CV trong pipeline chuẩn hơn vì tránh leak dữ liệu")
print("- Pipeline giúp fit transform đúng theo từng fold")

# Bài 4:
import pandas as pd
import joblib

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/ITA105_Lab_8.csv")

target = "SalePrice"
num_cols = ["LotArea", "Rooms", "HasGarage", "NoiseFeature"]
cat_cols = ["Neighborhood", "Condition"]
text_col = "Description"
date_col = "SaleDate"

X = df.drop(columns=[target])
y = df[target]

def flatten_text(x):
    return pd.Series(x.iloc[:, 0]).fillna("")

def date_features(x):
    s = pd.to_datetime(x.iloc[:, 0], errors="coerce")
    out = pd.DataFrame()
    out["month"] = s.dt.month.fillna(0)
    out["quarter"] = s.dt.quarter.fillna(0)
    return out

num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

text_pipe = Pipeline([
    ("to_text", FunctionTransformer(flatten_text, validate=False)),
    ("tfidf", TfidfVectorizer(max_features=10))
])

date_pipe = Pipeline([
    ("date", FunctionTransformer(date_features, validate=False))
])

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols),
    ("txt", text_pipe, [text_col]),
    ("date", date_pipe, [date_col])
])

final_model = Pipeline([
    ("prep", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

final_model.fit(X, y)

joblib.dump(final_model, "house_price_pipeline.joblib")
print("Đã lưu pipeline thành công")

def predict_price(new_data):
    model = joblib.load("house_price_pipeline.joblib")

    if isinstance(new_data, str):
        new_data = pd.read_csv(new_data)

    pred = model.predict(new_data)
    return pred

new_data = X.sample(3, random_state=1).copy()
new_data["Neighborhood"] = "NewPlace"

pred = predict_price(new_data)

print("Giá dự đoán:")
print(pred)